steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: 'bash'
    args:
      - -c
      - |
        docker build -t southamerica-west1-docker.pkg.dev/secret-drake-463714-u5/image-registry/orders-ms -f dockerfile.prod --platform=linux/amd64 --build-arg DATABASE_URL=$$DATABASE_URL .
    secretEnv: ['DATABASE_URL']
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "southamerica-west1-docker.pkg.dev/secret-drake-463714-u5/image-registry/orders-ms",
      ]
availableSecrets:
  secretManager:
  - versionName: projects/1020935777816/secrets/orders_db_url/versions/1
    env: 'DATABASE_URL'
options:
  logging: CLOUD_LOGGING_ONLY

